#!/bin/bash

echo "Building app.goodcity.hk [production]" && \
EMBER_CLI_CORDOVA=0 ember build --environment=production && \
echo "Removing existing files on app.goodcity.hk" && \
ssh deployer@app.goodcity.hk 'rm -rf /var/www/html/app.goodcity.hk/*' && \
echo "Uploading new files to app.goodcity.hk" && \
scp -r dist/* deployer@app.goodcity.hk:/var/www/html/app.goodcity.hk/
